# Input files
exp_mtx: "matrix.tsv"


# Database files
tf_list: "/home/hsun41/home/common/Databases/cistarget/tf_lists/allTFs_mm.txt"
databases:
  - "/home/hsun41/home/common/Databases/cistarget/databases/mm10.refseq_r80.mc_v10_clust/mm10_10kbp_up_10kbp_down_full_tx_v10_clust.genes_vs_motifs.rankings.feather"
  - "/home/hsun41/home/common/Databases/cistarget/databases/mm10.refseq_r80.mc_v10_clust/mm10_500bp_up_100bp_down_full_tx_v10_clust.genes_vs_motifs.rankings.feather"

# Annotation file
annotation_file: "/home/hsun41/home/common/Databases/cistarget/motif2tf/motifs-v10nr_clust-nr.mgi-m0.001-o0.0.tbl"


# Tools
tools:
  pyscenic: "/home/hsun41/software/miniconda3/envs/pyscenic/bin/pyscenic"

# Pipeline parameters
params:
  grn:
    seed: 42
    num_workers: 10
  ctx:
    num_workers: 10
  aucell:
    num_workers: 10




