
local:
  MM10_GENES: ~/onedrive/mydoc/database/mouse_genome/GRCm38_gencode_vM23/gtf/mm10_gencode_vM23.filtered.txt
  HG38_GENES: ~/onedrive/mydoc/database/human_genome/GRCh38_gencode_v32/gtf/grch38_gencode_v32.filtered.txt

hpc:
  RSCRIPT: /research/groups/mackgrp/home/common/Tools/ExTools/extra/miniconda3/envs/r_4.2.1/bin/Rscript
  MM10_GENES: /research/groups/mackgrp/home/common/Databases/mouse_genome/GRCm38_gencode_vM23/gtf/mm10_gencode_vM23.filtered.txt
  HG38_GENES: /research/groups/mackgrp/home/common/Databases/human_genome/GRCh38_gencode_v32/gtf/grch38_gencode_v32.filtered.txt
  
